#!/usr/bin/env python3

import sys
from pathlib import Path

# Add the processors directory to the path
sys.path.insert(0, str(Path(__file__).parent / "processors" / "disfluency_processor"))

from disfluency_processor import DisfluencyProcessor

def test_processor():
    """Test the improved disfluency processor."""
    
    # Initialize processor
    model_path = Path(__file__).parent / 'joint-disfluency-detector-and-parser' / 'best_models' / 'swbd_fisher_bert_Edev.0.9078.pt'
    processor = DisfluencyProcessor(str(model_path))
    
    # Test with a simple sentence containing disfluencies
    test_text = """[Interviewee] Leonardo Cipriani
There is something called shop drawings, which is like a technical drawing thing. Yeah, right. That you need to have some technical knowledge. Of course. Yes. But this is something that I know in this industry from every part of the industry."""
    
    print("Original text:")
    print(test_text)
    print("\n" + "="*80 + "\n")
    
    # Test the sentence splitting
    content = "There is something called shop drawings, which is like a technical drawing thing. Yeah, right. That you need to have some technical knowledge. Of course. Yes. But this is something that I know in this industry from every part of the industry."
    
    sentences = processor._split_into_sentences(content)
    print("Sentences generated by splitter:")
    for i, sentence in enumerate(sentences):
        print(f"{i+1}: '{sentence}'")
    print("\n" + "="*80 + "\n")
    
    # Process the text
    clean_text = processor.process_text(test_text)
    
    print("Processed text:")
    print(clean_text)

if __name__ == "__main__":
    test_processor()
